-- m_identity_columns schema 的前置状态
-- ensure() 端点首次创建 schema 后会执行本文件。
-- search_path 在执行前已被设置为 m_identity_columns, pg_catalog，所以下面的 SQL 不需要写完整 schema 限定。

CREATE TABLE t_serial (
  id   serial PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE t_identity (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE t_uuid (
  id   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL
);

-- SERIAL：不传 id，让序列推进
INSERT INTO t_serial (name) VALUES ('alpha'), ('beta'), ('gamma');

-- IDENTITY：不传 id，让 IDENTITY 序列推进
INSERT INTO t_identity (name) VALUES ('alpha'), ('beta'), ('gamma');

-- UUID：显式给固定 UUID，便于 example 引用
INSERT INTO t_uuid (id, name) VALUES
  ('00000000-0000-0000-0000-000000000001', 'alpha'),
  ('00000000-0000-0000-0000-000000000002', 'beta'),
  ('00000000-0000-0000-0000-000000000003', 'gamma')
ON CONFLICT (id) DO NOTHING;
